### ISSUE TITLE
我看 deployment.yaml 文件内容是空的，提供一个作为参考

### ISSUE THREAD

**Issue by junlintianxiazhifulinzhongguo** [kubehan/PromAI#17]
# 创建钉钉机器人，注意，关键词必须包含 巡检报告，并且要加签,加签后生成的secret 配置文件中会用到
![image](https://github.com/user-attachments/assets/6baf2471-4404-43a3-b1bc-13ecaeb98a75)





# 我这里因为本地使用的是 ingress 方式访问，所以没有在svc 中使用nodeport ,如果没有安装 ingress， 可以将svc中的type配置改成NodePort

# 创建命名空间
```
kubectl create ns promai
```

# 创建应用
```
kubectl apply -f deployment.yaml
```

# deployment.yaml 内容
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  namespace: promai
data:
  config.yaml: >-
    prometheus_url:
    "http://prometheus-k8s.kubesphere-monitoring-system.svc.cluster.local:9090"


    project_name: "测试项目巡检报告"


    # 定时任务：每天10点和17执行

    cron_schedule: "0 10,17 * * *"


    # 报告清理

    report_cleanup:
      enabled: true
      max_age: 7    # 保留最近7天的报告
      cron_schedule: "0 0 * * *" # 如果为空，则执行执行上面定时任务，即生成报告时清理

    # 配置发送钉钉和邮件

    notifications:
      dingtalk:
        enabled: true
        webhook: "https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxx"
        secret: "xxxxxxxxxxxxxxxxx"  # # 这个里面填的是钉钉机器人加签后自动生成的密钥
        report_url: "https://promai.lichengjun.top"  
      email:
        enabled: true
        smtp_host: "smtp.163.com"
        smtp_port: 465
        username: "xxx@163.com"
        password: "xxxxxxxxx"
        from: "xxxxx@163.com"
        to: 
          - "xxxx@163.com"
        report_url: "http://192.168.5.125:41174" 

    metric_types:
      - type: "基础资源使用情况"
        metrics:
          - name: "CPU使用率"
            description: "节点CPU使用率统计"
            query: "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode='idle'}[5m])) * 100)"
            threshold: 80
            threshold_type: "greater"
            unit: "%"
            labels:
              instance: "节点"
          
          - name: "内存使用率"
            description: "节点内存使用率统计"
            query: "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
            threshold: 85
            threshold_type: "greater"
            unit: "%"
            labels:
              instance: "节点"

          - name: "磁盘使用率"
            description: "节点磁盘使用率统计"
            query: >-
              (((100 -((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes)) 
              and ON (instance, device, mountpoint) node_filesystem_readonly{mountpoint!~"/run.*|/var.*|/boot.*|/tmp.*"}== 0) 
              + on(instance) group_left(node_uname_info) node_uname_info) 
              * on(instance) group_left(nodename) node_uname_info
            threshold: 80
            threshold_type: "greater"
            unit: "%"
            labels:
              instance: "节点"
              mountpoint: "挂载点"
              device: "磁盘"
              nodename: "节点名称"


          - name: "固定机器内存使用率"
            description: "固定机器内存使用率统计"
            query: >-
              100 - ((node_memory_MemAvailable_bytes{instance="172.16.5.132:9100"} * 100) / node_memory_MemTotal_bytes{instance="172.16.5.132:9100"})
            threshold: 16.84
            threshold_type: "greater"
            unit: "%"
            labels:
              instance: "节点"


      # - type: "PaaS平台巡检"
      #   metrics:
      #     - name: "K8s集群关键服务"
      #       description: "K8s集群关键服务状态统计"
      #       query: "key_pod_status"
      #       threshold: 1 
      #       threshold_type: "equal"
      #       unit: ""
      #       labels:
      #         component: "服务名称"
      #         namespace: "命名空间"
      #         # describe: "服务描述"
      #         hostname: "主机名称"
      #         owner: "负责人"
      #         instance: "节点"

      - type: "kubernetes集群监控状态"
        metrics:
          - name: "K8s集群巡检"
            description: "K8s集群巡检"
            query: "k8s_cluster_auto_check"
            threshold: 1
            threshold_type: "equal" 
            unit: ""
            labels:
              component: "服务名称"
              hostname: "主机名称"
              owner: "负责人"

          - name: "自定义监控脚本执行情况"
            description: "script-exporter监控脚本执行情况"
            query: "script_success"
            threshold: 1
            threshold_type: "equal"
            unit: ""
            labels:
              instance: "宿主机器"
              script: "脚本名称"
     
          - name: "Pod运行状态"
            description: "集群Pod运行状态统计"
            query: "sum by (namespace, pod) (kube_pod_status_phase{phase='Running',namespace='kube-system'})"
            threshold: 1
            threshold_type: "equal"
            unit: ""
            labels:
              namespace: "命名空间"
              pod: "Pod名称"

          - name: "节点就绪状态"
            description: "K8s节点就绪状态检查"
            query: "kube_node_status_condition{condition='Ready',status!='true'}"
            threshold: 0
            threshold_type: "equal"
            unit: ""
            labels:
              node: "节点"
              condition: "状态类型"

          - name: "PVC使用率"
            description: "持久化存储使用率"
            query: >-
              100 * (1 - kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes)
            threshold: 90
            threshold_type: "greater"
            unit: "%"
            labels:
              namespace: "命名空间"
              persistentvolumeclaim: "PVC名称"


---

kind: Service
apiVersion: v1
metadata:
  name: promai
  namespace: promai
  labels:
    app: promai
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 8091
  selector:
    app: promai
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: promai
  namespace: promai
  labels:
    app: promai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promai
  template:
    metadata:
      labels:
        app: promai
    spec:
      volumes:
        - name: volume-kv418v
          configMap:
            name: config
            defaultMode: 420
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''    
      containers:
        - name: promai
          image: 'kubehan/promai:latest'
          ports:
            - name: tcp-8091
              containerPort: 8091
              protocol: TCP
          env:
            - name: PROMETHEUS_URL
              value: >-
                http://prometheus-k8s.kubesphere-monitoring-system.svc.cluster.local:9090
          resources:
            limits:
              cpu: 20m
              memory: 20Mi
            requests:
              cpu: 5m
              memory: 15Mi
          volumeMounts:
            - name: volume-kv418v
              readOnly: true
              mountPath: /app/config
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime  
          livenessProbe:
            tcpSocket:
              port: 8091
            initialDelaySeconds: 15
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 8
          readinessProbe:
            tcpSocket:
              port: 8091
            initialDelaySeconds: 15
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 8
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```


# 钉钉效果

![image](https://github.com/user-attachments/assets/ac28cd93-6715-4d33-8870-c6fdbd4ee4e0)


# 邮箱效果
![image](https://github.com/user-attachments/assets/93320878-f0a3-4885-ac74-e269f9e33ad3)





--------------------------------------------------------------------------------------------------------------------------
# 经过测试发现，当前代码只能通过 ip+端口的访问访问，因为我部署在k8s中，所以需要通过域名访问，为此做了代码修改



# 修改部分：
## config/config.yaml
```
# 配置发送钉钉和邮件
notifications:
  dingtalk:
    enabled: true
    webhook: "https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    report_url: "http://192.168.5.125:41174"    # 增加该变量，并替换成自己的域名或者ip+端口
  email:
    enabled: true
    smtp_host: "smtp.exmail.qq.com"
    smtp_port: 465
    username: "lichengjun@demo.cn"
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    from: "lichengjun@demo.cn"
    to: 
      - "lichengjun@demo.cn"
    report_url: "https://promai.lichengjun.top"     # 增加该变量，并替换成自己的域名或者ip+端口
```

## pkg/notify/notify.go
```
import (
	//"PromAI/pkg/utils"   # 注释掉这行
	"bytes"



type DingtalkConfig struct {
	Enabled bool   `yaml:"enabled"`
	Webhook string `yaml:"webhook"`
	Secret  string `yaml:"secret"`
        ReportURL string `yaml:"report_url"`   # 增加该变量
}

type EmailConfig struct {
	Enabled  bool     `yaml:"enabled"`
	SMTPHost string   `yaml:"smtp_host"`
	SMTPPort int      `yaml:"smtp_port"`
	Username string   `yaml:"username"`
	Password string   `yaml:"password"`
	From     string   `yaml:"from"`
	To       []string `yaml:"to"`
        ReportURL string `yaml:"report_url"`     # 增加该变量
}


func SendDingtalk(config DingtalkConfig, reportPath string) error {
      // port := utils.GetGlobalPort()    # 注释掉这行
      // ip := utils.GetLocalIPs()[0]        # 注释掉这行
      
      // 正确生成报告的访问链接
      reportFileName := filepath.Base(reportPath)    # 增加该变量
      reportLink := fmt.Sprintf("%s/reports/%s", config.ReportURL, reportFileName)   # 增加该变量

      //修改消息内容成下面这个样子
      messageContent := map[string]interface{}{
		"msgtype": "markdown",
		"markdown": map[string]string{
			"title": "巡检报告",
			"text": fmt.Sprintf("## 🔍 巡检报告已生成\n\n"+
				"### ⏰ 生成时间\n"+
				"> %s\n\n"+
				"### 📄 报告详情\n"+
				"- **文件名**：`%s`\n"+    
				"- **访问链接**：[点击查看报告](%s)\n\n"+       # 修改访问链接
				"---\n"+
				"💡 请登录环境查看完整报告内容",
				time.Now().Format("2006-01-02 15:04:05"),
				reportFileName,                                            
                                reportLink),
		},
	}
}






# 下面的配置类似，以下只是提了要修改的部分，其他的不变
func SendEmail(config EmailConfig, reportPath string) error {
        // 设置邮件正文
	// port := utils.GetGlobalPort()
	// ip := utils.GetLocalIPs()[0]

	// 正确生成报告的访问链接
        reportFileName := filepath.Base(reportPath)
        reportLink := fmt.Sprintf("%s/reports/%s", config.ReportURL, reportFileName) 
     
       // 添加更丰富的邮件内容
	e.HTML = []byte(fmt.Sprintf(`
        <h2>🔍 巡检报告已生成</h2>
        <p><strong>生成时间：</strong>%s</p>
        <p><strong>报告文件：</strong>%s</p>
        <p><strong>在线查看：</strong><a href="%s">点击查看报告</a></p>
        <p><strong>请登录环境查看完整报告内容!</strong></p>
    `,
		time.Now().Format("2006-01-02 15:04:05"),
		reportFileName,
                reportLink))


}


```



# 修改后 完整的文件
## config.yaml
```
prometheus_url: "http://prometheus-k8s.kubesphere-monitoring-system.svc.cluster.local:9090"

project_name: "测试项目巡检报告"

# 定时任务：每天9点和18执行
cron_schedule: "37 11,17 * * *"

# 报告清理
report_cleanup:
  enabled: true
  max_age: 7    # 保留最近7天的报告
  cron_schedule: "0 0 * * *" # 如果为空，则执行执行上面定时任务，即生成报告时清理

# 配置发送钉钉和邮件
notifications:
  dingtalk:
    enabled: true
    webhook: "https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    report_url: "http://192.168.5.125:41174"
  email:
    enabled: true
    smtp_host: "smtp.exmail.qq.com"
    smtp_port: 465
    username: "lichengjun@demo.cn"
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    from: "lichengjun@demo.cn"
    to: 
      - "lichengjun@demo.cn"
    report_url: "https://promai.lichengjun.top"  

metric_types:
  - type: "基础资源使用情况"
    metrics:
      - name: "CPU使用率"
        description: "节点CPU使用率统计"
        query: "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode='idle'}[5m])) * 100)"
        threshold: 80
        threshold_type: "greater"
        unit: "%"
        labels:
          instance: "节点"
      
      - name: "内存使用率"
        description: "节点内存使用率统计"
        query: "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
        threshold: 85
        threshold_type: "greater"
        unit: "%"
        labels:
          instance: "节点"

      - name: "磁盘使用率"
        description: "节点磁盘使用率统计"
        query: >-
          (((100 -((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes)) 
          and ON (instance, device, mountpoint) node_filesystem_readonly{mountpoint!~"/run.*|/var.*|/boot.*|/tmp.*"}== 0) 
          + on(instance) group_left(node_uname_info) node_uname_info) 
          * on(instance) group_left(nodename) node_uname_info
        threshold: 80
        threshold_type: "greater"
        unit: "%"
        labels:
          instance: "节点"
          mountpoint: "挂载点"
          device: "磁盘"
          nodename: "节点名称"


      - name: "固定机器内存使用率"
        description: "固定机器内存使用率统计"
        query: >-
          100 - ((node_memory_MemAvailable_bytes{instance="172.16.5.132:9100"} * 100) / node_memory_MemTotal_bytes{instance="172.16.5.132:9100"})
        threshold: 16.84
        threshold_type: "greater"
        unit: "%"
        labels:
          instance: "节点"


  # - type: "PaaS平台巡检"
  #   metrics:
  #     - name: "K8s集群关键服务"
  #       description: "K8s集群关键服务状态统计"
  #       query: "key_pod_status"
  #       threshold: 1 
  #       threshold_type: "equal"
  #       unit: ""
  #       labels:
  #         component: "服务名称"
  #         namespace: "命名空间"
  #         # describe: "服务描述"
  #         hostname: "主机名称"
  #         owner: "负责人"
  #         instance: "节点"

  - type: "kubernetes集群监控状态"
    metrics:
      - name: "K8s集群巡检"
        description: "K8s集群巡检"
        query: "k8s_cluster_auto_check"
        threshold: 1
        threshold_type: "equal" 
        unit: ""
        labels:
          component: "服务名称"
          hostname: "主机名称"
          owner: "负责人"

      - name: "自定义监控脚本执行情况"
        description: "script-exporter监控脚本执行情况"
        query: "script_success"
        threshold: 1
        threshold_type: "equal"
        unit: ""
        labels:
          instance: "宿主机器"
          script: "脚本名称"
 
      - name: "Pod运行状态"
        description: "集群Pod运行状态统计"
        query: "sum by (namespace, pod) (kube_pod_status_phase{phase='Running',namespace='kube-system'})"
        threshold: 1
        threshold_type: "equal"
        unit: ""
        labels:
          namespace: "命名空间"
          pod: "Pod名称"

      - name: "节点就绪状态"
        description: "K8s节点就绪状态检查"
        query: "kube_node_status_condition{condition='Ready',status!='true'}"
        threshold: 0
        threshold_type: "equal"
        unit: ""
        labels:
          node: "节点"
          condition: "状态类型"

      - name: "PVC使用率"
        description: "持久化存储使用率"
        query: >-
          100 * (1 - kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes)
        threshold: 90
        threshold_type: "greater"
        unit: "%"
        labels:
          namespace: "命名空间"
          persistentvolumeclaim: "PVC名称"

```

# pkg/notify/notify.go

```
package notify

import (
	//"PromAI/pkg/utils"
	"bytes"
	"crypto/hmac"
	"crypto/sha256"
	"crypto/tls"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"mime/multipart"
	"net/http"
	"net/smtp"
	"net/url"
	"os"
	"path/filepath"
	"time"

	"github.com/jordan-wright/email"
)

type DingtalkConfig struct {
	Enabled bool   `yaml:"enabled"`
	Webhook string `yaml:"webhook"`
	Secret  string `yaml:"secret"`
    ReportURL string `yaml:"report_url"`
}

type EmailConfig struct {
	Enabled  bool     `yaml:"enabled"`
	SMTPHost string   `yaml:"smtp_host"`
	SMTPPort int      `yaml:"smtp_port"`
	Username string   `yaml:"username"`
	Password string   `yaml:"password"`
	From     string   `yaml:"from"`
	To       []string `yaml:"to"`
    ReportURL string `yaml:"report_url"`
}

// config/config.yaml 中 dingtalk 配置
// notifications:
//   dingtalk:
//     enabled: true
//     webhook: "https://oapi.dingtalk.com/robot/send?access_token=29f727c8c973e5fb8d8339968d059393a4b4bb0bdcd667d592996035a8c0e135"
//     secret: "SEC75fd20834b42064b86c1aa97930738befeb2fe214044649397752212c5894848"

// SendDingtalk 发送钉钉通知
func SendDingtalk(config DingtalkConfig, reportPath string) error {
	if !config.Enabled {
		log.Printf("钉钉通知未启用")
		return nil
	}
	log.Printf("开始发送钉钉通知...")
	// 计算时间戳和签名
	timestamp := time.Now().UnixMilli()
	sign := calculateDingtalkSign(timestamp, config.Secret)
	webhook := fmt.Sprintf("%s&timestamp=%d&sign=%s", config.Webhook, timestamp, sign)

	log.Printf("准备发送请求到 webhook: %s", webhook)
	// 创建multipart表单
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	// 添加文件
	file, err := os.Open(reportPath)
	if err != nil {
		log.Printf("打开文件失败: %v", err)
		return fmt.Errorf("打开文件失败: %v", err)
	}
	defer file.Close()

	part, err := writer.CreateFormFile("file", filepath.Base(reportPath))
	if err != nil {
		log.Printf("创建表单文件失败: %v", err)
		return fmt.Errorf("创建表单文件失败: %v", err)
	}

	fileContent, err := os.ReadFile(reportPath)
	if err != nil {
		log.Printf("读取文件失败: %v", err)
		return fmt.Errorf("读取文件失败: %v", err)
	}
	part.Write(fileContent)

	// port := utils.GetGlobalPort()
	// ip := utils.GetLocalIPs()[0]

	// 正确生成报告的访问链接
        reportFileName := filepath.Base(reportPath)
        reportLink := fmt.Sprintf("%s/reports/%s", config.ReportURL, reportFileName) 

	// 添加消息内容
	messageContent := map[string]interface{}{
		"msgtype": "markdown",
		"markdown": map[string]string{
			"title": "巡检报告",
			"text": fmt.Sprintf("## 🔍 巡检报告已生成\n\n"+
				"### ⏰ 生成时间\n"+
				"> %s\n\n"+
				"### 📄 报告详情\n"+
				"- **文件名**：`%s`\n"+
				"- **访问链接**：[点击查看报告](%s)\n\n"+
				"---\n"+
				"💡 请登录环境查看完整报告内容",
				time.Now().Format("2006-01-02 15:04:05"),
				reportFileName,
                                reportLink),
		},
	}

	jsonData, err := json.Marshal(messageContent)
	if err != nil {
		log.Printf("JSON编码失败: %v", err)
		return fmt.Errorf("JSON编码失败: %v", err)
	}

	// 发送请求
	req, err := http.NewRequest("POST", webhook, bytes.NewBuffer(jsonData))
	if err != nil {
		log.Printf("创建请求失败: %v", err)
		return fmt.Errorf("创建请求失败: %v", err)
	}
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		log.Printf("发送请求失败: %v", err)
		return fmt.Errorf("发送请求失败: %v", err)
	}
	defer resp.Body.Close()
	respBody, _ := io.ReadAll(resp.Body)
	log.Printf("钉钉响应状态码: %d, 响应内容: %s", resp.StatusCode, string(respBody))

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("钉钉发送失败，状态码: %d", resp.StatusCode)
	}

	log.Printf("钉钉通知发送成功")
	return nil
}

// SendEmail 发送邮件通知
func SendEmail(config EmailConfig, reportPath string) error {
	if !config.Enabled {
		log.Printf("邮件通知未启用")
		return nil
	}

	log.Printf("开始发送邮件通知...")
	log.Printf("SMTP服务器: %s:%d", config.SMTPHost, config.SMTPPort)
	log.Printf("发件人: %s", config.From)
	log.Printf("收件人: %v", config.To)

	e := email.NewEmail()
	e.From = config.From
	e.To = config.To
	e.Subject = "巡检报告"

	// 设置邮件正文
	// port := utils.GetGlobalPort()
	// ip := utils.GetLocalIPs()[0]

	// 正确生成报告的访问链接
        reportFileName := filepath.Base(reportPath)
        reportLink := fmt.Sprintf("%s/reports/%s", config.ReportURL, reportFileName) 

	// 添加更丰富的邮件内容
	e.HTML = []byte(fmt.Sprintf(`
        <h2>🔍 巡检报告已生成</h2>
        <p><strong>生成时间：</strong>%s</p>
        <p><strong>报告文件：</strong>%s</p>
        <p><strong>在线查看：</strong><a href="%s">点击查看报告</a></p>
        <p><strong>请登录环境查看完整报告内容!</strong></p>
    `,
		time.Now().Format("2006-01-02 15:04:05"),
		reportFileName,
                reportLink))

	// 添加附件
	if _, err := e.AttachFile(reportPath); err != nil {
		log.Printf("添加附件失败: %v", err)
		return fmt.Errorf("添加附件失败: %v", err)
	}

	// 发送邮件（使用TLS）
	addr := fmt.Sprintf("%s:%d", config.SMTPHost, config.SMTPPort)
	auth := smtp.PlainAuth("", config.Username, config.Password, config.SMTPHost)

	tlsConfig := &tls.Config{
		InsecureSkipVerify: true,
		ServerName:         config.SMTPHost,
	}

	log.Printf("正在发送邮件...")
	if err := e.SendWithTLS(addr, auth, tlsConfig); err != nil {
		log.Printf("发送邮件失败: %v", err)
		log.Printf("SMTP配置信息:")
		log.Printf("- 服务器: %s", config.SMTPHost)
		log.Printf("- 端口: %d", config.SMTPPort)
		log.Printf("- 用户名: %s", config.Username)
		return fmt.Errorf("发送邮件失败: %v", err)
	}

	log.Printf("邮件发送成功")
	return nil
}

// calculateDingtalkSign 计算钉钉签名
func calculateDingtalkSign(timestamp int64, secret string) string {
	stringToSign := fmt.Sprintf("%d\n%s", timestamp, secret)
	h := hmac.New(sha256.New, []byte(secret))
	h.Write([]byte(stringToSign))
	return url.QueryEscape(base64.StdEncoding.EncodeToString(h.Sum(nil)))
}

```


# 修改完成后，重新构建命令

```
[root@tools PromAI]# go build -o PromAI main.go
[root@tools PromAI]# ls
config  deploy  Dockerfile  Dockerfile1  go1.22.3.linux-amd64.tar.gz  go.mod  go.sum  images  main.go  outputs  pkg  PromAI  PromAI.exe  promai.tar.gz  README.md  reports  templates
[root@tools PromAI]#

```

# 重新打包成镜像
```
[root@tools PromAI]# docker build -t k8s/promai:v3  .
[+] Building 32.0s (17/17) FINISHED                                                                                                                                                                                     docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                                              0.0s
 => => transferring dockerfile: 717B                                                                                                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/alpine:3.21.0                                                                                                                                                                  5.0s
 => [internal] load metadata for docker.io/library/golang:1.23.4-alpine3.20                                                                                                                                                       4.3s
 => [internal] load .dockerignore                                                                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                                                   0.0s
 => [internal] load build context                                                                                                                                                                                                 0.2s
 => => transferring context: 15.48MB                                                                                                                                                                                              0.1s
 => [stage-1 1/7] FROM docker.io/library/alpine:3.21.0@sha256:21dc6063fd678b478f57c0e13f47560d0ea4eeba26dfc947b2a4f81f686b9f45                                                                                                    0.0s
 => [builder 1/4] FROM docker.io/library/golang:1.23.4-alpine3.20@sha256:6a84ccdb73e005d0ee7bfff6066f230612ca9dff3e88e31bfc752523c3a271f8                                                                                         0.0s
 => CACHED [builder 2/4] WORKDIR /build                                                                                                                                                                                           0.0s
 => [builder 3/4] COPY . .                                                                                                                                                                                                        1.9s
 => [builder 4/4] RUN go env -w GO111MODULE=on &&  go mod download && go build && ls -la /build                                                                                                                                  24.0s
 => CACHED [stage-1 2/7] WORKDIR /app                                                                                                                                                                                             0.0s
 => [stage-1 3/7] COPY --from=builder /build/PromAI /app/                                                                                                                                                                         0.0s
 => [stage-1 4/7] COPY --from=builder /build/config /app/config/                                                                                                                                                                  0.1s
 => [stage-1 5/7] COPY --from=builder /build/outputs /app/outputs/                                                                                                                                                                0.0s
 => [stage-1 6/7] COPY --from=builder /build/reports /app/reports/                                                                                                                                                                0.1s
 => [stage-1 7/7] COPY --from=builder /build/templates /app/templates/                                                                                                                                                            0.0s
 => exporting to image                                                                                                                                                                                                            0.4s
 => => exporting layers                                                                                                                                                                                                           0.4s
 => => writing image sha256:9773ab636410716556f3e182b9e50c900e09da414bd03a971e4864e59dcae7ba                                                                                                                                      0.0s
 => => naming to docker.io/k8s/promai:v3                                                                                                                                                                                          0.0s
[root@tools PromAI]#

```


# 在k8s中替换镜像后，测试效果

![Image](https://github.com/user-attachments/assets/e7daa53a-d999-4c26-8762-a670fa14805b)

![Image](https://github.com/user-attachments/assets/e1dd841a-04fe-4c3a-b612-1daa43b0f259)
